version: 2.1
jobs:
  build:
    docker:
      - image: node:14

    working_directory: /app

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: yarn install

      - run:
          name: Build
          command: yarn build

  deploy_preview:
    docker:
      - image: node:14

    working_directory: /app

    steps:
      - checkout

      - run:
          name: Install Vercel CLI
          command: npm install -g vercel

      - run:
          name: Deploy to Vercel (Preview)
          command: vercel --prod --token $VERCEL_TOKEN --confirm

  deploy_prod:
    docker:
      - image: node:14

    working_directory: /app

    steps:
      - checkout

      - run:
          name: Manual Approval Required
          command: echo "Please manually approve the production deployment in the CircleCI workflow."

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy_preview:
          requires:
            - build
          filters:
            branches:
              only:
                - main
      - deploy_prod:
          requires:
            - deploy_preview
          type: approval
