version: 2.1
jobs:
  preview_deployment:
    docker:
      - image: cimg/node:20.10.0
    environment:
      VERCEL_ORG_ID: fFjAMdHDYJf2ciD2fO1Qr9ji
      VERCEL_PROJECT_ID: prj_qfD0UT3oA0O7WBd6FOdt9eCIy7v7
    steps:
      - checkout
      - run:
          name: Install Vercel CLI
          command: npm i -g vercel
      - run:
          name: Pull Vercel Environment Information
          command: vercel pull --yes --environment=preview
      - run:
          name: Build Project Artifacts
          command: vercel build
      - run:
          name: Deploy Project Artifacts to Vercel
          command: vercel deploy --prebuilt

  production_deployment:
    docker:
      - image: cimg/node:20.10.0
    environment:
      VERCEL_ORG_ID: fFjAMdHDYJf2ciD2fO1Qr9ji
      VERCEL_PROJECT_ID: prj_33VA0B09u0wHez4ysULXy3wHhaXs
      APPROVAL_FLAG: ''
    steps:
      - checkout
      - run:
          name: Install Vercel CLI
          command: npm i -g vercel
      - run:
          name: Pull Vercel Environment Information
          command: vercel pull --yes --environment=production
      - run:
          name: Add production environment to Vercel
          command: echo -n 'true' | vercel env add TRIGGER_PROD_BUILD production  ;
      - run:
          name: See env variables
          command: vercel env ls
      - run:
          name: Deploy Project Artifacts to Vercel
          command: vercel deploy --no-wait --prod
      - run:
          name: Remove production environment from Vercel
          command: vercel env rm --yes TRIGGER_PROD_BUILD production
      - run:
          name: See env variables
          command: vercel env ls

workflows:
  version: 2
  preview_and_production:
    jobs:
      - preview_deployment:
          filters:
            branches:
              ignore: /main/
      - hold_for_approval:
          type: approval
          filters:
            branches:
              only: /main/
      - production_deployment:
          requires:
            - hold_for_approval
          filters:
            branches:
              only: /main/
