version: 2.1
jobs:
  build:
    docker:
      - image: node:18

    working_directory: /app
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install

      - run:
          name: Build
          command: yarn build

  deploy:
    docker:
      - image:  node:18

    working_directory: /app

    steps:
      - checkout

      - run:
          name: Install Vercel CLI
          command: npm install -g vercel

      - run:
          name: Deploy to Vercel
          command: |
            if [ "$CIRCLE_BRANCH" == "main" ]; then
              echo "Manual approval required for production deployment. Visit the CircleCI dashboard to approve."
            else
              vercel --prod --token $VERCEL_TOKEN --yes
            fi


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build



