version: 2.1
jobs:
  preview_deployment:
    docker:
      - image: cimg/node:20.10.0
    environment:
      VERCEL_ORG_ID: $VERCEL_ORG_ID
      VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID
    steps:
      - checkout
      - run:
          name: Install Vercel CLI
          command: npm i -g vercel
      - run:
          name: Pull Vercel Environment Information
          command: vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
      - run:
          name: Build Project Artifacts
          command: vercel build --token=$VERCEL_TOKEN
      - run:
          name: Deploy Project Artifacts to Vercel
          command: vercel deploy --prebuilt --token=$VERCEL_TOKEN

  production_deployment:
    docker:
      - image: cimg/node:20.10.0
    environment:
      VERCEL_ORG_ID: $VERCEL_ORG_ID
      VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID
    steps:
      - checkout
      - run:
          name: Install Vercel CLI
          command: npm i -g vercel
      - run:
          name: Pull Vercel Environment Information
          command: vercel pull --yes --environment=production --token=$VERCEL_TOKEN
      - run:
          name: Add production environment to Vercel
          command: echo -n 'true' | vercel env add TRIGGER_PROD_BUILD production --token=$VERCEL_TOKEN ;
      - run:
          name: See env variables
          command: vercel env ls --token=$VERCEL_TOKEN
      - run:
          name: Deploy Project Artifacts to Vercel
          command: vercel deploy --no-wait --prod --token=$VERCEL_TOKEN
      - run:
          name: Remove production environment from Vercel
          command: vercel env rm --yes TRIGGER_PROD_BUILD production --token=$VERCEL_TOKEN
      - run:
          name: See env variables
          command: vercel env ls --token=$VERCEL_TOKEN

workflows:
  version: 2
  preview_and_production:
    jobs:
      - preview_deployment:
          filters:
            branches:
              ignore: /main/
      - hold_for_approval:
          type: approval
          filters:
            branches:
              only: /main/
      - production_deployment:
          requires:
            - hold_for_approval
          filters:
            branches:
              only: /main/
