version: 2.1

jobs:
  deploy_to_vercel:
    docker:
      - image: cimg/node:14.17.6
    steps:
      - checkout
      - run:
          name: Install Vercel CLI
          command: npm i -g vercel
      - run:
          name: Deploy to Vercel
          command: vercel deploy --prod --token=VERCEL_TOKEN

  hold_for_approval:
    docker:
      - image: cimg/node:14.17.6
    steps:
      - checkout
      - run:
          name: Hold for approval
          command: echo "Waiting for approval..."

workflows:
  version: 2
  deploy_to_vercel:
    jobs:
      - deploy_to_vercel:
          filters:
            branches:
              only:
                - main
      - hold_for_approval:
          type: approval
          filters:
            branches:
              only:
                - main
