version: 2.1
jobs:
  build:
    docker:
      - image: node:21

    working_directory: /app

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: yarn install

      - run:
          name: Build
          command: yarn build

  deploy:
    docker:
      - image: cimg/base:2021.10

    working_directory: /app

    steps:
      - checkout

      - run:
          name: Deploy to Vercel
          command: |
            curl -o vercel.tgz -sSL https://cdn.vercel.com/download/linux -x
            tar -xzf vercel.tgz -C /usr/local/bin
            vercel --version
            vercel --prod --token $VERCEL_TOKEN

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
