version: 2.1
jobs:
  build:
    docker:
      - image: node:18

    working_directory: /app
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install

      - run:
          name: Build
          command: yarn build

  deploy:
    docker:
      - image:  node:18

    working_directory: /app

    steps:
      - checkout

      - run:
          name: Install Vercel CLI
          command: npm install -g vercel

      - run:
          name: Deploy to Vercel
          command: |
            echo $VERCEL_TOKEN | vercel login
            vercel --prod --token $VERCEL_TOKEN --yes

  hold_for_approval:
    docker:
      - image: cimg/node:18
    steps:
      - checkout
      - run:
          name: Hold for approval
          command: echo "Waiting for approval..."


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - hold_for_approval:
          type: approval
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branchs:
              only:
                - main



